import { useQuery } from "@tanstack/react-query";
import { Battery, FlaskConical, History, Map, RadioTower, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { useWallet } from "@/contexts/WalletContext";
import { useDigitalTwin } from "@/hooks/useDigitalTwin";
import { appWalletApi } from "@/lib/api";
import SimulationDisclosure from "@/components/SimulationDisclosure";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function Dashboard() {
  const { demoProfile, demoSessionId, demoJoinCode, demoKit, wallet } = useWallet();
  const { data: twin } = useDigitalTwin(demoSessionId);
  const { data: walletData } = useQuery({ queryKey: ["wallet-ledger", wallet?.id], queryFn: appWalletApi.get, refetchInterval: 2500 });
  const currentWallet = walletData?.wallet || wallet;
  return <main className="min-h-screen px-4 pb-16 pt-24"><div className="container mx-auto max-w-6xl"><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{demoProfile === "donor" ? "Donor" : "Receiver"} operations</h1><Badge variant="outline" className="font-mono">Session {demoJoinCode}</Badge></div><p className="mt-2 text-sm text-muted-foreground">App wallet, Power Kit and Delhi NCR market state in one operational view.</p></div><SimulationDisclosure /></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={WalletCards} label="Available" value={`${currentWallet?.balance.toFixed(4) || "0.0000"} LT`} /><Metric icon={History} label="Escrow" value={`${currentWallet?.escrow_balance.toFixed(6) || "0.000000"} LT`} /><Metric icon={Battery} label="Fleet average SoC" value={`${twin?.average_soc.toFixed(1) || "--"}%`} /><Metric icon={RadioTower} label="Active transfers" value={String(twin?.active_transfers ?? "--")} /></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><Card><CardHeader><CardTitle className="text-sm">Your sample Power Kit</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-3"><Info label="MAC identity" value={demoKit?.mac_address || "--"} mono /><Info label="Location" value={demoKit?.location || "--"} /><Info label="Hardware profile" value="5V / 18650 prototype" /></div><div className="mt-4 flex flex-wrap gap-2"><Button asChild size="sm"><Link to="/marketplace">Open market</Link></Button><Button asChild size="sm" variant="outline"><Link to="/device/register">Register hardware</Link></Button><Button asChild size="sm" variant="outline"><Link to="/network"><Map className="mr-2 h-4 w-4" />View network</Link></Button></div></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><History className="h-4 w-4 text-primary" />Immutable LT ledger</CardTitle></CardHeader><CardContent>{walletData?.ledger?.length ? <div className="responsive-table"><table className="w-full min-w-[560px] text-left text-xs"><thead className="text-[9px] uppercase tracking-widest text-muted-foreground"><tr><th>Entry</th><th>Description</th><th>Amount</th><th>Balance</th><th>Escrow</th></tr></thead><tbody>{walletData.ledger.map((entry: any) => <tr key={entry.id} className="border-t border-border"><td className="py-3 font-mono">{entry.entry_type}</td><td>{entry.description}</td><td className="font-mono">{entry.amount.toFixed(6)} LT</td><td className="font-mono">{entry.balance_after.toFixed(6)}</td><td className="font-mono">{entry.escrow_after.toFixed(6)}</td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">Ledger entries appear after demo funding or trade actions.</p>}</CardContent></Card></div>
      <aside className="space-y-5"><Card><CardHeader><CardTitle className="text-sm">Market conditions</CardTitle></CardHeader><CardContent className="space-y-3"><Info label="Price" value={`${twin?.price_lt_per_kwh.toFixed(4) || "--"} LT/kWh`} /><Info label="Simulated timestamp" value={twin ? new Date(twin.simulated_at).toLocaleString() : "--"} /><Info label="Weather source" value={twin?.weather.source || "--"} /><Info label="Weather" value={twin ? `${twin.weather.temperature_c.toFixed(1)} C, ${twin.weather.cloud_cover_pct.toFixed(0)}% cloud` : "--"} /></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><FlaskConical className="h-4 w-4 text-primary" />Experimental Labs</CardTitle></CardHeader><CardContent><p className="text-xs leading-relaxed text-muted-foreground">Optional Soroban proofs, DeFi, yield, flash lending and governance remain research modules. No APY or earned value is claimed in the product dashboard.</p><Badge variant="outline" className="mt-4 text-[10px]">Non-production research</Badge></CardContent></Card></aside></div>
  </div></main>;
}
function Metric({ icon: Icon, label, value }: { icon: any; label: string; value: string }) { return <div className="metric-panel"><Icon className="h-4 w-4 text-primary" /><p className="mt-3 font-mono text-lg font-semibold">{value}</p><p className="mt-1 text-[9px] uppercase tracking-widest text-muted-foreground">{label}</p></div>; }
function Info({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="rounded border border-border bg-secondary/30 p-3"><p className="text-[9px] uppercase tracking-widest text-muted-foreground">{label}</p><p className={`mt-1 break-words text-xs font-medium ${mono ? "font-mono" : ""}`}>{value}</p></div>; }
