[workspace]
members = [
    "contracts/energy_token",
    "contracts/marketplace",
    "contracts/network_incentives",
    "contracts/governance",
]
resolver = "2"

[profile.release]
opt-level = "z"
overflow-checks = false # Changed to false for extreme space saving
debug = false
panic = "abort"
lto = true
codegen-units = 1
strip = true # Added strip
[profile.release-with-logs]
inherits = "release"
debug = true
